### ISSUE TITLE
How to use selectedItemURLs in Automator Workflows?

### ISSUE THREAD

**Issue by Tekl** [knurling/ServiceStation#14]
The Variable selectedItemURLs seems to be a string surrounded by parentheses. Actions like copying the selected files don't work with this.

**Comment by pkamb** [comment]
If you press the `Sample Scripts` button, the resulting directory will have a Scripts readme as well as samples for the 4 script types.

 The automator workflow there will display the values of the 3 variables when run.

`selectedItemURLs` is passed in as an array of the selected file URL paths. This is displayed as a parentheses-wrapped list of quoted paths:

![Screen Shot 2020-04-16 at 4 31 02 PM](https://user-images.githubusercontent.com/342355/79516239-ab90c100-7fff-11ea-9802-135ba4ca1014.png)

You are right that this list is not parsed correctly/expectedly by some Automator actions.

"Open Finder Items" works for the single `targetedURL` variable, but not for the array of `selectedItemURLs`:

![Screen Shot 2020-04-16 at 4 29 11 PM](https://user-images.githubusercontent.com/342355/79516331-e8f54e80-7fff-11ea-80ff-0bcf2f741eae.png)

That "Open Finder Items" action should take multiple items...

I'll be investigating how to get those URLs into the correct Automator multiple item list format.

**Comment by pkamb** [comment]
I'm still unsure why the multi-path array variable is unable to be read by `Open Finder Items` and other actions, as detailed in the SO question above.

However, I'm going to begin additionally sending the selected files as input to the automator workflow. This will work more like a Service, with no need to grab the data from variables before using it. I'll continue to set the variables as well if they are declared in the workflow.

Look for that in the next App Store update, which I'll be submitting very soon.

**Comment by pkamb** [comment]
Version 2020.3 was released to the Mac App Store this morning:

 - Passes selected files and folders as input to Automator workflows

I'd love to hear how this update works for your Automator workflows @Tekl

**Comment by Tekl** [comment]
Whoohooo. Thanks a lot. It works well. Btw. a way to open or reveal scripts from within Service Station would be a great addition.

**Comment by gingerbeardman** [comment]
@Tekl perhaps that last comment is covered by #8 ?
