### ISSUE TITLE
Keyboard shortcut to action

### ISSUE THREAD

**Issue by venkatasg** [knurling/ServiceStation#15]
Is there a way to set keyboard shortcuts to new items (scripts and applications) in the Finder right-click menu? This would make it so much more useful.

**Comment by pkamb** [comment]
By this you mean that you would select items in the Finder, then press a keyboard shortcut to activate a script or open with an application? Not opening the context menu at all?

The Finder Sync Extension framework doesn't have any provisions for keyboard shortcuts in that manner.

It's a good idea... but Service Station would need an entirely new way to get the selected items in Finder. Which might not be possible at all in the Mac App Store Sandbox.

I'll keep it in mind for down the road, especially if the Finder Extension framework adds any keyboard accommodations.

For the moment, this kind of keyboard-launched scripting can be accomplished through apps such as FastScripts: https://red-sweater.com/fastscripts/

**Comment by pkamb** [comment]
Michael Tsai also mentioned this when he linked Service Station:

 > I’m a keyboard person, so I have done this sort of thing by writing AppleScripts (BBEdit, Preview, Terminal) and invoking them via [FastScripts](https://red-sweater.com/fastscripts/).

 > https://mjtsai.com/blog/2020/04/14/service-station-1-0/

**Comment by venkatasg** [comment]
Ah ok, I didn't realise that was a limitation of the API. I was also confused by the 'Service' in the name - I thought it meant adding items to the Services list in Keyboard shortcuts
