### ISSUE TITLE
Service Station Finder Extension: multiple running processes

### ISSUE THREAD

**Issue by pkamb** [knurling/ServiceStation#17]
When I open Activity Monitor, I see multiple copies of the Service Station Finder Extension running:

![Screen Shot 2020-04-16 at 7 00 24 PM](https://user-images.githubusercontent.com/342355/79524408-52cc2300-8015-11ea-8284-d375a31a9daa.png)

Why are there multiple copies of the Service Station Finder Sync Extension process running??

**Comment by pkamb** [comment]
This is expected behavior for macOS Finder Sync Extensions and not a bug or performance problem specific to Service Station.

MacOS may launch multiple copies of a Finder Extension in response to various actions in Finder.

 > ### Performance Concerns

 > Finder Sync extensions may have a much longer lifespan than most other extensions. Because of this long lifespan, you must take particular care to avoid any possible performance issues. Ideally, Finder Sync extensions should spend most of their time running but idle. Limit the number of resources the extension consumes. Most important, be sure to avoid leaking any resources. Over time, even a small trickle can grow into a serious problem.

 > The system may also launch **additional copies of your extension** whenever an Open or Save dialog is displayed. This means that **the user may have multiple copies of your extension running at once**, and some may be very short lived. Therefore, it’s generally best if the extension focuses on handling the badges, contextual menus, and toolbar buttons. Place in a separate service (a Login Item or Launch Agent) any code that performs the sync, updates state, or communicates with remote data sources. This approach ensures that there is only one syncing service running at a time.

 > https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Finder.html

**Comment by pkamb** [comment]
Service Station received a poor review due to this macOS behavior. Reposting my developer response to hopefully assist other developers or app users who may be investigating the same.

 > Slow perfomance, invasive ★☆☆☆☆
 > Feb 1, 2021
 >
 > This app opens many "lightweight background apps" that totaled about 8 or 9 open instances, thrioughout just about every aspect of MacOS. This seems like a privacy and performance nightmare, which it proved to be. I got notices from the system constantly, and my default search would change constantly even though I had adjusted the settings
 >
 > DO. NOT. GET. THIS.

Service Station uses only the modern Finder extension points provided by Apple. Absolutely no "hacks" or other deceptive behavior.

It's normal macOS operating procedure (unfortunately) for the system to open multiple copies of the background process. App developers have no control over how many macOS launches. A new copy is opened for each Sandboxed view of Finder. 

Please see issue #17 on the Service Station support site for a complete discussion of this issue. It may look bad to see multiple copies in Activity Monitor, but I assure you that this is how Finder Extensions are designed to work by Apple.

**Comment by gilby101** [comment]
I don't know if this is any consolation, but that negative review does not appear on all App Stores.  The two reviews on the AU App Store are both 5/5.
