### ISSUE TITLE
Contextual menu item is disabled

### ISSUE THREAD

**Issue by alakoring** [knurling/ServiceStation#18]
I added Visual Studio to open text files. It shows up in the contextual menu, but is always dim.
<img width="259" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/12171257/79618010-bca00780-80bd-11ea-9232-69381b6316c9.png">

It is possible that I have to pay for this, but that was not clear. The app has no help.

**Comment by pkamb** [comment]
This is one of the limitations of the Free version: 3 menu items per menu. Any others can be added but will be greyed out.

Sorry for the confusion in this first version. I'll be adding better UI explaining this, and documentation, in upcoming releases.

https://github.com/knurling/ServiceStation/issues/1
