### ISSUE TITLE
Remove non-Service Station right-click menu options?

### ISSUE THREAD

**Issue by colinjrobertson** [knurling/ServiceStation#23]
1. Can you _not_ have the 'service station' icon in the right-click menu?
2. Can I use the app to remove Dropbox's annoying 'Move to Dropbox' and 'Send with Transfer...' right-click menu items?

My desired use case for this app is to clean up my right-click menus like I use Bartender to clean up my menu bar items. Let me know if this isn't what the app is for... Thanks!

**Comment by pkamb** [comment]
1. The Service Station menu item is always shown in the free Version if any other Service Station menu items will be shown for a particular menu. Upgrade to Pro via the IAP to remove it.

   (*Or, of course, uninstall Service Station and/or disable it's Finder Extension if you don't actually want to use any Service Station menu items.*)

2. Dropbox uses the same Finder Extension technology that Service Station does. You can enable any Finder Extension individually in `System Preferences > Extensions > Finder Extensions`. Turn off Dropbox there.

 > My desired use case for this app is to clean up my right-click menus like I use Bartender to clean up my menu bar items. Let me know if this isn't what the app is for.

Service Station is used to **add** items to the context menu. It can't really remove anything.

However, this is a common feature request for people who are using Service Station to customize their right-click menu. So I'm going to start compiling and writing tips for that as well, such as:

 - [Remove 'Tags' section from macOS Finder right-click context menu
](https://apple.stackexchange.com/questions/387849/remove-tags-section-from-macos-finder-right-click-context-menu)

**Comment by colinjrobertson** [comment]
This is helpful—thanks. I just wish I could disable those dropbox items that specifically show up outside of dropbox. I like the ability to right-click to copy a dropbox folder link...

**Comment by gingerbeardman** [comment]
> This is helpful—thanks. I just wish I could disable those dropbox items that specifically show up outside of dropbox. I like the ability to right-click to copy a dropbox folder link...

As Dropbox for finer grained control. 

OR

Switch off all Dropbox context menu integration and create your own "Copy to Dropbox" menu using a script in ServiceStation! Should be quite easy.

**Comment by pkamb** [comment]
The "Move to Dropbox" menu item can be disabled individually, which I had forgotten I had done on my machine at some point in the past:
https://apple.stackexchange.com/questions/219659/remove-move-to-dropbox-menu-from-finder-context-menu

This "Send with Transfer..." menu item is new. Not sure if it can be disabled selectively without disabling Dropbox's entire Finder Extension. I asked a question for that here:
https://apple.stackexchange.com/questions/389415/remove-dropbox-send-with-transfer-item-from-finder-context-menu
