### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by petebocken** [knurling/ServiceStation#24]
Need uninstaller or uninstall instructions.

**Comment by gingerbeardman** [comment]
@petebocken just delete the app

**Comment by pkamb** [comment]
To uninstall:

 - Close Service Station
 - Delete `Service Station.app` from your Applications folder.

To keep the Service Station app but remove it entirely from your Finder menu:

 - System Preferences > Extensions > Finder Extensions
 - Uncheck `Service Station Finder Extension`
