### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by rk492** [knurling/ServiceStation#26]
Hi! I am trying to contact you by private channels, but I couldn't do it. It's not a bug or suggestion. I wanted to contact you because I could translate app to Spanish if you want.

**Comment by pkamb** [comment]
Hi, thanks for the suggestion. Localization is on my list. I will contact you down the line when I'm able to add it - thanks!

**Comment by pkamb** [comment]
closing in favor of a ticket at #27
