### ISSUE TITLE
What are the differences between the Free and Pro versions?

### ISSUE THREAD

**Issue by VKondakoff** [knurling/ServiceStation#29]
Hello!

Looks like this info is unavailable on the site and the App Store.
What are the differences between ServiceStation Free and Pro versions?

Thank you!

**Comment by pkamb** [comment]
The Free version you can download from the Mac App Store has the limitations:

 - 4 filetype rules
 - 3 menu items in any given menu
 - "Service Station" menu item added to the end of each menu

Any additional menu items will be grayed out in your Finder Extension menu.

Service Station includes an in-app purchase to unlock unlimited rules and menu items.

As an independent Mac app developer, thank you for your support :)

**Comment by VKondakoff** [comment]
Thanks, got it!
