### ISSUE TITLE
Is it normal for multiple copies of the Finder Extension process to be running?

### ISSUE THREAD

**Issue by luckman212** [knurling/ServiceStation#31]
Sorry to hear about v2020.5 being rejected by the MAS Gods! Good luck getting it pushed thru...

In the meantime, I'm still running v2020.4 and today noticed quite a few (7 to be exact) copies of **Service Station Finder Extension** running. Is this "normal" ?

![image](https://user-images.githubusercontent.com/1992842/81627951-51e8a000-93cd-11ea-8385-1c732a7c0dd5.png)

**Comment by pkamb** [comment]
Yes, this is expected behavior. macOS spawns multiple processes for Finder Extensions, so you more often than not end up with a couple running at any given time.

more details and quotes from the docs here: #17

**Comment by luckman212** [comment]
Ah I see now. Thanks, I didn't see those docs before. 👍
