### ISSUE TITLE
Updating SS disables Service Station Attendant

### ISSUE THREAD

**Issue by VKondakoff** [knurling/ServiceStation#37]
Hello!

Just noticed, scripts stopped to work after latest SS update (to Version 2020.5 (18)). They are still available in the mouse right-click menu, but there is nothing happened, when you choose them.

Here is what I saw, when first I was thinking, there are some issues with the content of the scripts, but here is what I saw, when I open the main SS window:

<img width="805" alt="Скриншот 2020-05-14 15 13 34" src="https://user-images.githubusercontent.com/230824/81933997-e255f900-95f6-11ea-9a3b-b2de061ddd78.png">

So, it seems updating SS disables Service Station Attendant. All the scripts are working again after re-enabling it. 
I think SS Attendant should be re-enabled automatically during update, or (at least), there should be a message to the user that SS Attendant should bу re-enabled for SS to work properly.

**Comment by VKondakoff** [comment]
Or, maybe, there should be a warning message 'SS Attendant is not enabled', when user is trying to run a script and SS Attendant is ...mmm... not enabled?.. ;)

**Comment by pkamb** [comment]
Having the `Service Station Attendant` background process off by default, and allowing the user to enable/disable it, was an App Store Review requirement for shipping 2020.5: #28 

So, the main app now prompts at app launch and at termination for you to enable the Attendant. Once you have manually clicked "Enable" once (satisfying App Store Review), that setting is saved and you will not be asked again.

The Attendant is always running when the main app is; the setting only changes the state when the main app quits.

The attendant can also be toggled in the `System Setup` menu bar item.

---

I think the issue you're reporting is:

1. Used an old version of Service Station. Attendant is enabled by default.
2. Updated to version 2020.5.
3. Did NOT launch 2020.5. Finder Extension continued to run.
4. Clicked a menu item but nothing happened (meaning the Attendant is not running).

From my understanding of the system, that should not happen. I would expect the old version Finder Extension and old version Attendant to continue running until the new version main app is launched. At that point, the old version of the Attendant is quit and the new version launched (added in 2020.4 #20). If you then quit the app without enabling the Attendant for background use, it will not be available when the Finder Extension needs to use it.

Is it possible that you launched 2020.5, didn't enable the attendant, and then ran into these problems?

I had to make this change quickly to satisfy App Review and get the update out the door. In the future, I'd like to present an error dialog or FAQ if you activate a menu item via the Finder Extension but the background process is not running. That situation should notify the user that background process needs to be enabled for Service Station to function.

**Comment by VKondakoff** [comment]
> Used an old version of Service Station. Attendant is enabled by default.
> Updated to version 2020.5.
> Did NOT launch 2020.5. Finder Extension continued to run.
> Clicked a menu item but nothing happened (meaning the Attendant is not running).

As far as I understand, this is exactly what happened.

> I would expect the old version Finder Extension and old version Attendant to continue running until the new version main app is launched.

Looks like for some reason there was old Finder Extension and new version Attendant. As far as I remember, the system was not restarted after updating SS, but it was put in the Sleep mode and then woke up.

> Is it possible that you launched 2020.5, didn't enable the attendant, and then ran into these problems?

No, I'm pretty sure I never launched updated SS (2020.5) until I noticed issues with Finder Extension. 

I think this issue is quite rare and not harmful. Just wanted you to know about the possible problem. Ready to test something, if needed.

**Comment by pkamb** [comment]
> I think this issue is quite rare and not harmful. Just wanted you to know about the possible problem. Ready to test something, if needed.

Thank you. I'll keep my eye on this and continue testing app-update scenarios. Closing this ticket for now.
