### ISSUE TITLE
SS Version 2020.5 (18) does not work on network drive

### ISSUE THREAD

**Issue by VKondakoff** [knurling/ServiceStation#39]
Just tried to open .txt file from mounted network drive using SS Finder extension. Nothing happens when you choose the menu item:

<img width="530" alt="Скриншот 2020-05-14 23 29 20" src="https://user-images.githubusercontent.com/230824/81983032-63cf7a80-963b-11ea-8feb-8f69743e637d.png">

The Backup (smb://VK-DS._smb._tcp.local/Backup) is added to SS Finder locations:

<img width="567" alt="Скриншот 2020-05-14 23 28 35" src="https://user-images.githubusercontent.com/230824/81983110-83ff3980-963b-11ea-8305-15923ef60e1c.png">

VSCode is added as a target for .txt files:

<img width="567" alt="Скриншот 2020-05-14 23 28 22" src="https://user-images.githubusercontent.com/230824/81983239-b872f580-963b-11ea-8eee-cbe508e11bfa.png">

What's wrong here?

Catalina 10.15.4

**Comment by pkamb** [comment]
If the menu item appears but nothing happens when you click it, it indicates that the `Service Station Attendant` process is either not running or does not match the version of the main app and/or Finder Extension

Similar to the problem you had here:
https://github.com/knurling/ServiceStation/issues/37

Try turning off the attendant via the menu bar, then quitting the app. Then launch the main app and Enable the attendant again. To be fully sure, try logging out or rebooting.

Sorry for the trouble... I'll be adding better error messages in future versions.

**Comment by VKondakoff** [comment]
I think SS Attendant was running, because I was able to use menu items on local disk, but not on network disk. Right now, when I tried to reproduce the issue on network disk SS asked me for permission to access network drives and after I granted the permission, menu item works as expected. There was no such a request yesterday, when I reported the issue.

Can this be a permission issue?

**Comment by pkamb** [comment]
Ah, `Removable Volumes` and `Network Drives` *are* "Files and Folders" permissions in Catalina:

https://nektony.com/duplicate-finder-free/folders-permission

You can either grant those individual checkboxes or grant "Full Disk Access" to grant all locations.

Service Station does prompt for access in Desktop, Documents, and the other needed locations. I would expect you to have seen that permission alert yesterday, especially if you see it now.

It should prompt for permission the first time you try to use Service Station in such a location. I'll do some testing with this in Catalina with external volumes.

**Comment by VKondakoff** [comment]
Just wanted to note: there was _no_ prompt for permission when I first reported the issue. The prompt appeared next day, when I tried to reproduce the issue again (after system restart, I suppose). Not sure if this is SS or Catalina issue.

**Comment by pkamb** [comment]
Strange that it did not prompt the first time. I'll keep an eye on this. Closing for the time being, as this is working once that permission is added.
