### ISSUE TITLE
Allow menu items with no icon

### ISSUE THREAD

**Issue by pkamb** [knurling/ServiceStation#4]
Currently, Service Station menu items always have icons.

The menu items use the same icon as the Application or Script file that will be run. In the worst case, they would use the default "blank" file icon.

Icons can be a huge benefit to recognition in the menu, and mimic the icons in the "Open With" menu. But they're at odds with the no-icons top-level macOS menu. There may be situations where having no icon is preferred.  

### Service Station should allow menu items without icons.

![Screen Shot 2020-03-20 at 6 04 17 PM](https://user-images.githubusercontent.com/342355/79371642-8a4da900-7f09-11ea-9cac-5cbea7fb7bca.png)

**Comment by gingerbeardman** [comment]
This is annoying for me because I mainly use shell scripts, and they're all associated with my text editor. So I have a bunch of text editor icons in my menu.

Which raises question about custom icons per menu item? But perhaps that's another issue for another day.

**Comment by pkamb** [comment]
> Which raises question about custom icons per menu item?

This is possible today, if you set a custom icon for the script file itself:  
https://apple.stackexchange.com/questions/116595/add-a-custom-icon-to-os-x-folder

Service Station will pick up any custom icons you assign via Finder, so that is definitely a way to give scripts unique icons in the Service Station menu.

 > https://sixcolors.com/post/2020/04/service-station-adds-control-over-finder-menus/

 > 
![service-jpeg-6c non-retina non-retina](https://user-images.githubusercontent.com/342355/80700383-7b7efe80-8a92-11ea-8220-41d66c4778cd.jpg)

**Comment by pkamb** [comment]
I've submitted version 2020.4 for review, which adds the ability to Hide Icons for individual menu items. I'll update when that is available on the Mac App Store.

**Comment by pkamb** [comment]
After a quick review, [v2020.4](https://github.com/knurling/ServiceStation/releases/tag/v2020.4) is now available on the Mac App Store.

Please give `Hide Icon` a try and let me know how it works for your scripts and if there are any problems.

**Comment by gingerbeardman** [comment]
This works OK, but I would prefer a way to have this default to Hidden for all items.
