### ISSUE TITLE
Duplicate items should be filtered so only 1 is shown

### ISSUE THREAD

**Issue by luckman212** [knurling/ServiceStation#41]
I have **Sublime Text** registered as an item for **Text** as well as **Any**:
![image](https://user-images.githubusercontent.com/1992842/82084706-b51e4f00-96b9-11ea-9566-c8c9face8efa.png)

This causes it to appear twice in the SS menu:
![image](https://user-images.githubusercontent.com/1992842/82084913-278f2f00-96ba-11ea-8e66-1cb2cc298823.png)

It would be good for items to be de-duped before the menu is rendered if they are identical.

**Comment by weavermedia** [comment]
Which one should be filtered out? Should it show the first one that matches? Or the one that matches most specifically (ie by matching the most rules)? Or another filter method?

**Comment by luckman212** [comment]
I think they should all be shown, but filtered so that exact duplicate actions (e.g. identical App bundle or script path) should only show a single result.

**Comment by weavermedia** [comment]
Indeed, but I was asking which duplicate(s) should be omitted and which single instance should be shown? That will affect the placement of the item in the menu. In your example would you expect to see:

Sublime Text
TextEdit
Xcode

or

TextEdit
Xcode
Sublime Text

This would be more pronounced the longer the menu list as you would expect to see an item in a certain place every time.

Also, if you have an app/script in the 'Any' rule wouldn't it just be easier to not add it to any other more specific rules?

**Comment by luckman212** [comment]
I'm imagining programmatically it would be easier to skip the duplicate items when building the array of menuitems, rather than remove the previous entries and reinsert them at the end. So it would be

Sublime Text
TextEdit
Xcode

And yes—you're right about just not adding the "Any" items to the other categories as a partial solution. I realized that some time after my original post, just forgot to comment.

**Comment by pkamb** [comment]
Thanks for this suggestion! Duplicates will be removed in version `2020.9`, coming soon to the Mac App Store.

The order of menu items is determined by the order of Rules/Items in the UI. This change keeps the first exact-duplicate Item and hides the rest.

---

Old:

<img width="211" alt="Screen Shot 2020-12-07 at 2 49 39 PM" src="https://user-images.githubusercontent.com/342355/101415187-565e3400-389c-11eb-8a31-6634015ed886.png">

New:

<img width="209" alt="Screen Shot 2020-12-07 at 2 50 00 PM" src="https://user-images.githubusercontent.com/342355/101415203-5e1dd880-389c-11eb-90ff-0328ce1bd544.png">

**Comment by luckman212** [comment]
Love it!

**Comment by pkamb** [comment]
Very fast Mac App Store Review. This is now released in v2020.9 🚀
