### ISSUE TITLE
Multiple instances of the Finder Extension running

### ISSUE THREAD

**Issue by gavinjerman** [knurling/ServiceStation#46]
Is it normal for there to be multiple, currently 7, instances of the Service Station Finder Extension running? I rebooted yesterday and the number of instances running has crept up again, and I haven't used SS since the reboot.

<img width="796" alt="service station finder extension" src="https://user-images.githubusercontent.com/30599841/87554771-75b9b200-c6ac-11ea-8e99-6b1f91bd930b.png">

**Comment by gingerbeardman** [comment]
Yes, by macOS design.

See #31 and #17
