### ISSUE TITLE
Pearl [sic] Script?

### ISSUE THREAD

**Issue by luckman212** [knurling/ServiceStation#50]
It's Pedantry time!

I think there's a typo here...
![image](https://user-images.githubusercontent.com/1992842/96353188-dd124400-1097-11eb-89f6-08fd549fafaa.png)

If you happen to be in there making changes, "Apple Script" is also not correct. it should be **AppleScript** (no space).

**Comment by pkamb** [comment]
Thank you and great eye!

Sorry for the delay. Fixed in the upcoming version. fde5e8c
