### ISSUE TITLE
Not able to use Preview 

### ISSUE THREAD

**Issue by vfl97** [knurling/ServiceStation#52]
As you can see in the screenshot, preview is greyed out and that's why I can't use this app. I've already reinstalled Servicestation.

![screen](https://user-images.githubusercontent.com/15114846/100896921-6b634d80-34bf-11eb-9100-fa28b48b7e74.png)

**Comment by gingerbeardman** [comment]
Is this because it's already the default to open that type of file?

**Comment by pkamb** [comment]
If you drag Preview up into one of the first 3 slots it will become usable in the Free version. Or, purchase Service Station Pro IAP (via the "Purchase") button to have more than 3 menu items.

Free version limitations:

 - 4 filetype rules
 - 3 menu items in any given menu
 - "Service Station" menu item added to the end of each menu

https://github.com/knurling/ServiceStation/issues/1
