### ISSUE TITLE
Finder extension duplicate processes

### ISSUE THREAD

**Issue by bryanheinz** [knurling/ServiceStation#54]
If you disable the Finder extension the extension process never quits. If you then re-enable it, a new Finder extension process is spawned.

Reproduction steps:
- Open Activity Monitor, search for "service station finder"
- Open System Preferences -> Extensions -> Finder Extensions
- Uncheck "Service Station Finder Extension"
- Notice the process is still there in Activity Monitor
- Check "Service Station Finder Extension"
- Notice a new Finder extension process is spawned with the old one still there

I've currently got 7 of these processes running as I was trying to track a problem down 😅 I figured I'd open an issue to let you know!

-bryan

**Comment by gingerbeardman** [comment]
See issue: #17 it is pinned at the top of the issues list because it is asked often.

**Comment by bryanheinz** [comment]
🤦‍♂️ i didn't search closed issues.

**Comment by gingerbeardman** [comment]
![2021-01-12 00_21_01-Greenshot](https://user-images.githubusercontent.com/49612/104253369-2e9a5700-546c-11eb-98cc-c673b47572bb.png)

**Comment by pkamb** [comment]
thanks @bryanheinz and @gingerbeardman - I added an FAQ section to the README to make these common trouble spots easier to find.
