### ISSUE TITLE
How to move Service Station's Open With . . . options within the right-click menu?

### ISSUE THREAD

**Issue by AvonGee** [knurling/ServiceStation#66]
All of the screenshots [here](https://servicestation.menu/features/open-with-applications) show the custom Open With . . . options appearing directly below the standard Open With > item in the right-click Finder menu. But when I run Service Station, all of the custom options appear way down after Quick Actions. I don't want them down there—how do I move them up?

**Comment by SteveMattan** [comment]
It seems that this is an issue introduced in Big Sur and continued in Monterey. 

See issue #48

**Comment by AvonGee** [comment]
Missed that, thank you Steve.
